<a href="https://colab.research.google.com/github/Hyolinkim/capstoneDesign_20210830/blob/main/DataScaling_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
filename='/content/drive/MyDrive/Sensorlog/raw/Normal/Normal_case1.csv'

In [3]:
#io와 pandas 모듈 import
import io
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
from numpy import nan as NA
import matplotlib.pyplot as plt

In [5]:
#pandas read_csv로 불러오기
data = pd.read_csv(filename)
data

     SamplingTime   AccelerationX  ...   MagneticFieldY   MagneticFieldZ
0    1.634224e+09        3.847632  ...
1    1.634224e+09        2.772186  ...
2    1.634224e+09        1.490989  ...
3    1.634224e+09        1.026364  ...
4    1.634224e+09        1.401955  ...
..            ...             ...  ...              ...              ...
365  1.634224e+09        0.568473  ...
366  1.634224e+09        0.188693  ...
367  1.634224e+09        0.866701  ...
368  1.634224e+09        0.789338  ...
369  1.634224e+09        1.195754  ...

[370 rows x 10 columns]

In [27]:
#pandas read_csv로 불러오기
data = pd.read_csv(filename)
data.columns = ['SamplingTime','AcX', 'AcY','AcZ','GyroX','GyroY','GyroZ','-','-','-']

In [28]:
data=data.drop(['-'],axis=1)
data

     SamplingTime       AcX       AcY        AcZ     GyroX     GyroY     GyroZ
0    1.634224e+09  3.847632  0.392799 -11.241974  0.027641  0.256422  0.084062
1    1.634224e+09  2.772186  0.459986 -10.265888  0.153584 -0.648855 -0.019739
2    1.634224e+09  1.490989  0.257227  -9.591471  0.136139 -0.359047  0.067926
3    1.634224e+09  1.026364  0.119710  -9.373000  0.085454  0.138633  0.134667
4    1.634224e+09  1.401955  0.300472  -9.733627  0.020570  0.251520  0.085002
..            ...       ...       ...        ...       ...       ...       ...
365  1.634224e+09  0.568473  9.201815  -3.655497  0.006941  0.006003 -0.027824
366  1.634224e+09  0.188693  9.473557  -1.850568  0.412038 -0.048566  0.002275
367  1.634224e+09  0.866701  8.859145  -3.272125  0.143755 -0.035549 -0.112164
368  1.634224e+09  0.789338  9.228450  -3.700987 -0.155576 -0.034637 -0.123747
369  1.634224e+09  1.195754  9.570073  -4.214543 -0.227895 -0.419473 -0.136811

[370 rows x 7 columns]

In [31]:
data_df=data[['AcX', 'AcY','AcZ','GyroX','GyroY','GyroZ']]
data_st=data[['SamplingTime']]
data_df

          AcX       AcY        AcZ     GyroX     GyroY     GyroZ
0    3.847632  0.392799 -11.241974  0.027641  0.256422  0.084062
1    2.772186  0.459986 -10.265888  0.153584 -0.648855 -0.019739
2    1.490989  0.257227  -9.591471  0.136139 -0.359047  0.067926
3    1.026364  0.119710  -9.373000  0.085454  0.138633  0.134667
4    1.401955  0.300472  -9.733627  0.020570  0.251520  0.085002
..        ...       ...        ...       ...       ...       ...
365  0.568473  9.201815  -3.655497  0.006941  0.006003 -0.027824
366  0.188693  9.473557  -1.850568  0.412038 -0.048566  0.002275
367  0.866701  8.859145  -3.272125  0.143755 -0.035549 -0.112164
368  0.789338  9.228450  -3.700987 -0.155576 -0.034637 -0.123747
369  1.195754  9.570073  -4.214543 -0.227895 -0.419473 -0.136811

[370 rows x 6 columns]

In [30]:
#정규화
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler()
transformer.fit(data_df)
data_df = transformer.transform(data_df)
print(data_df)

[[1.         0.44542254 0.01228357 0.5020742  0.69232486 0.65002109]
 [0.72812545 0.4484236  0.0913033  0.51335948 0.20535577 0.56140847]
 [0.4042367  0.4393669  0.1459012  0.5117963  0.36125009 0.63624614]
 ...
 [0.24641565 0.82359155 0.65748831 0.51247874 0.53526702 0.48250729]
 [0.22685816 0.84008741 0.62276949 0.48565683 0.53575761 0.47261914]
 [0.3296008  0.8553468  0.5811942  0.47917659 0.32874557 0.46146669]]

In [32]:
dataset=pd.DataFrame(data_df)
dataset

          AcX       AcY        AcZ     GyroX     GyroY     GyroZ
0    3.847632  0.392799 -11.241974  0.027641  0.256422  0.084062
1    2.772186  0.459986 -10.265888  0.153584 -0.648855 -0.019739
2    1.490989  0.257227  -9.591471  0.136139 -0.359047  0.067926
3    1.026364  0.119710  -9.373000  0.085454  0.138633  0.134667
4    1.401955  0.300472  -9.733627  0.020570  0.251520  0.085002
..        ...       ...        ...       ...       ...       ...
365  0.568473  9.201815  -3.655497  0.006941  0.006003 -0.027824
366  0.188693  9.473557  -1.850568  0.412038 -0.048566  0.002275
367  0.866701  8.859145  -3.272125  0.143755 -0.035549 -0.112164
368  0.789338  9.228450  -3.700987 -0.155576 -0.034637 -0.123747
369  1.195754  9.570073  -4.214543 -0.227895 -0.419473 -0.136811

[370 rows x 6 columns]

In [34]:
data_final=pd.concat([data_st,dataset], axis=1)
data_final

     SamplingTime       AcX       AcY        AcZ     GyroX     GyroY     GyroZ
0    1.634224e+09  3.847632  0.392799 -11.241974  0.027641  0.256422  0.084062
1    1.634224e+09  2.772186  0.459986 -10.265888  0.153584 -0.648855 -0.019739
2    1.634224e+09  1.490989  0.257227  -9.591471  0.136139 -0.359047  0.067926
3    1.634224e+09  1.026364  0.119710  -9.373000  0.085454  0.138633  0.134667
4    1.634224e+09  1.401955  0.300472  -9.733627  0.020570  0.251520  0.085002
..            ...       ...       ...        ...       ...       ...       ...
365  1.634224e+09  0.568473  9.201815  -3.655497  0.006941  0.006003 -0.027824
366  1.634224e+09  0.188693  9.473557  -1.850568  0.412038 -0.048566  0.002275
367  1.634224e+09  0.866701  8.859145  -3.272125  0.143755 -0.035549 -0.112164
368  1.634224e+09  0.789338  9.228450  -3.700987 -0.155576 -0.034637 -0.123747
369  1.634224e+09  1.195754  9.570073  -4.214543 -0.227895 -0.419473 -0.136811

[370 rows x 7 columns]

In [35]:
data_final['label']=0
data_final

     SamplingTime       AcX       AcY  ...     GyroY     GyroZ  label
0    1.634224e+09  3.847632  0.392799  ...  0.256422  0.084062      0
1    1.634224e+09  2.772186  0.459986  ... -0.648855 -0.019739      0
2    1.634224e+09  1.490989  0.257227  ... -0.359047  0.067926      0
3    1.634224e+09  1.026364  0.119710  ...  0.138633  0.134667      0
4    1.634224e+09  1.401955  0.300472  ...  0.251520  0.085002      0
..            ...       ...       ...  ...       ...       ...    ...
365  1.634224e+09  0.568473  9.201815  ...  0.006003 -0.027824      0
366  1.634224e+09  0.188693  9.473557  ... -0.048566  0.002275      0
367  1.634224e+09  0.866701  8.859145  ... -0.035549 -0.112164      0
368  1.634224e+09  0.789338  9.228450  ... -0.034637 -0.123747      0
369  1.634224e+09  1.195754  9.570073  ... -0.419473 -0.136811      0

[370 rows x 8 columns]

In [36]:
data_final.to_csv('/content/drive/MyDrive/Sensorlog/Scaling/Normal_Scaling_case1.csv')